import type { CourseCategoryReference, CourseTopicReference } from "@/lib/course-references"
import type { ParsedCoursePage } from "@/lib/course-html-parser"

const TOPIC_BODY_CLASS: Record<string, string> = {
  "learning-strategies": "page-education",
  "k-12-resources": "page-k12",
  "higher-education": "page-higher",
  "teaching-tools": "page-teaching",
  "student-success": "page-student",
  entrepreneurship: "page-entrepreneur",
  "business-strategy": "page-biz-strategy",
  management: "page-management",
  leadership: "page-leadership",
  sales: "page-sales",
  bookkeeping: "page-bookkeeping",
  "financial-analysis": "page-financial-analysis",
  "corporate-finance": "page-corporate-finance",
  investment: "page-investment",
  tax: "page-tax",
  "cloud-computing": "page-cloud",
  cybersecurity: "page-cyber",
  "it-support": "page-it-support",
  "dev-ops": "page-devops",
  networking: "page-networking",
  "ui-ux-design": "page-uiux",
  "graphic-design": "page-graphic",
  illustration: "page-illustration",
  "design-systems": "page-systems",
  "3d-design": "page-3d",
  excel: "page-excel",
  "google-workspace": "page-workspace",
  "project-planning": "page-planning",
  "time-management": "page-time",
  documentation: "page-docs",
  "digital-marketing": "page-digital",
  "content-strategy": "page-content",
  seo: "page-seo",
  branding: "page-branding",
  analytics: "page-analytics",
  "web-development": "page-webdev",
  "mobile-development": "page-mobile",
  "programming-languages": "page-languages",
  "game-development": "page-game",
  "database-design-and-development": "page-database",
  "software-testing": "page-testing",
  nutrition: "page-nutrition",
  yoga: "page-yoga",
  "mental-wellness": "page-mental",
  "fitness-training": "page-fitness",
  "health-coaching": "page-coaching",
  "music-production": "page-production",
  guitar: "page-guitar",
  piano: "page-piano",
  "music-theory": "page-theory",
  "sound-design": "page-sound",
}

function cardTitle(topicLabel: string, label: string) {
  return `${topicLabel}: ${label}`
}

export function buildCoursePage(
  category: CourseCategoryReference,
  topic: CourseTopicReference
): ParsedCoursePage {
  const bodyClassName = TOPIC_BODY_CLASS[topic.slug] ?? "page-education"
  const pageTitle = `${topic.label} Courses`
  const tabs = ["Most popular", "New", "Trending"]

  const panels = [
    {
      key: "most popular",
      cards: [
        {
          thumbClass: "edu-card__thumb edu-card__thumb--ai",
          title: cardTitle(topic.label, "Core Foundations"),
          meta: `${category.label} · LearnLab`,
          rating: "4.8 ★★★★★ (4,112)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--night",
          title: cardTitle(topic.label, "Practical Workflow"),
          meta: "Maya Liu",
          rating: "4.7 ★★★★★ (3,190)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--wall",
          title: cardTitle(topic.label, "Real Projects"),
          meta: "Chris Haroun | 1.5M Students",
          rating: "4.6 ★★★★★ (29,410)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--team",
          title: cardTitle(topic.label, "Systems & Mastery"),
          meta: "365 Careers",
          rating: "4.6 ★★★★★ (22,827)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
      ],
    },
    {
      key: "new",
      cards: [
        {
          thumbClass: "edu-card__thumb edu-card__thumb--truck",
          title: cardTitle(topic.label, "Starter Path"),
          meta: "SkillHub Academy",
          rating: "5.0 ★★★★★ (66)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--marketing",
          title: cardTitle(topic.label, "Updated Techniques"),
          meta: "ExpertEase",
          rating: "4.6 ★★★★★ (518)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--n8n",
          title: cardTitle(topic.label, "From Zero to Confident"),
          meta: "KRISHAI Technologies",
          rating: "4.9 ★★★★★ (399)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--idea",
          title: cardTitle(topic.label, "Hands-on Challenge"),
          meta: "Digit Rise Academy",
          rating: "4.8 ★★★★★ (113)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
      ],
    },
    {
      key: "trending",
      cards: [
        {
          thumbClass: "edu-card__thumb edu-card__thumb--ai",
          title: cardTitle(topic.label, "Career Track"),
          meta: "Ed Donner",
          rating: "4.7 ★★★★★ (3,688)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--class",
          title: cardTitle(topic.label, "Weekly Sprint"),
          meta: "Evan Kimbrell",
          rating: "4.7 ★★★★★ (25,428)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--rocket",
          title: cardTitle(topic.label, "Build Your Portfolio"),
          meta: "Chris Haroun | 1.5M Students",
          rating: "4.7 ★★★★★ (23,806)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
        {
          thumbClass: "edu-card__thumb edu-card__thumb--wall",
          title: cardTitle(topic.label, "Advanced Strategy"),
          meta: "365 Careers",
          rating: "4.5 ★★★★★ (62,932)",
          price: "Free",
          badges: ["Highest Rated", "Highest Views"],
        },
      ],
    },
  ]

  return {
    bodyClassName,
    pageTitle,
    pageSubhead: "Courses to get you started",
    pageDescription: "Explore courses from experienced, real-world experts.",
    tabs,
    panels,
    featuredTitle: "Featured course",
    featuredDescription: "Many learners enjoyed this highly rated course for its engaging content.",
    featured: {
      thumbClass: "edu-feature__thumb edu-feature__thumb--n8n",
      title: `${topic.label} Mastery: From Zero to Top Results`,
      description: `Build a complete ${topic.label.toLowerCase()} system with practical plans and step-by-step execution.`,
      metaLines: ["By LearnLab Academy and 2 other", "Updated February 2026 · 20 total hours · 132 lectures · All Levels"],
      rating: "4.8 ★★★★★ (712)",
      badges: ["Highest Rated", "Highest Views"],
      price: "Free",
    },
    topics: [
      topic.label,
      "Fundamentals",
      "Practical Projects",
      "Best Practices",
      "Career Growth",
      "Tooling",
      "Case Studies",
      "Real-world Workflow",
      "Planning",
      "Advanced Tips",
    ],
    instructorsTitle: "Popular Instructors",
    instructorsDescription: "These real-world experts are highly rated by learners like you.",
    instructors: [
      {
        avatarClass: "edu-instructor__avatar edu-instructor__avatar--one",
        name: "Maya Liu | 1.2 Million Students",
        meta: `${topic.label}, ${category.label}`,
        stats: ["4.7 ★ Instructor Rating", "1,204,921 students", "36 courses"],
      },
      {
        avatarClass: "edu-instructor__avatar edu-instructor__avatar--two",
        name: "Andrew Williams",
        meta: "Industry Practice, Systems",
        stats: ["4.6 ★ Instructor Rating", "482,117 students", "21 courses"],
      },
      {
        avatarClass: "edu-instructor__avatar edu-instructor__avatar--three",
        name: "Learning Lab",
        meta: "Project-based Learning",
        stats: ["4.8 ★ Instructor Rating", "912,540 students", "42 courses"],
      },
      {
        avatarClass: "edu-instructor__avatar edu-instructor__avatar--four",
        name: "Robin & Jesper",
        meta: "Focus, Productivity Systems",
        stats: ["4.6 ★ Instructor Rating", "556,953 students", "17 courses"],
      },
    ],
    allCoursesTitle: `All ${topic.label} courses`,
    notice: "Not sure? All courses have a 30-day money-back guarantee",
    sortBy: "Most Popular",
    resultsCount: "5,308 results",
    filters: [
      {
        title: "Ratings",
        options: ["4.5 & up (2,051)", "4.0 & up (4,012)", "3.5 & up (4,477)", "3.0 & up (4,577)"],
      },
      {
        title: "Video Duration",
        options: ["0-1 Hour (1,019)", "1-3 Hours (2,541)", "3-6 Hours (1,108)", "6-17 Hours (544)"],
      },
      {
        title: "Level",
        options: ["All Levels (2,785)", "Beginner (2,101)", "Intermediate (368)", "Expert (54)"],
      },
      {
        title: "Language",
        options: ["English (3,339)", "Espanol (413)", "Turkce (65)", "Portugues (456)"],
      },
    ],
    rows: [
      {
        thumbClass: "edu-row__thumb edu-row__thumb--wall",
        title: `${topic.label} Essentials: From Basics to Mastery`,
        text: `A complete system for ${topic.label.toLowerCase()} with practical workflows.`,
        meta: ["Chris Haroun | 1.5M Students", "8 total hours · 86 lectures · All Levels"],
        rating: "4.6 ★★★★★ (18,932)",
        badges: ["Highest Rated", "Highest Views"],
        price: "Free",
      },
      {
        thumbClass: "edu-row__thumb edu-row__thumb--class",
        title: `${topic.label} Bootcamp: Learn Faster in Weeks`,
        text: "Build a consistent routine with projects and practice sets.",
        meta: ["Evan Kimbrell", "7.5 total hours · 91 lectures · Beginner"],
        rating: "4.7 ★★★★★ (25,428)",
        badges: ["Highest Rated", "Highest Views"],
        price: "Free",
      },
      {
        thumbClass: "edu-row__thumb edu-row__thumb--rocket",
        title: `${topic.label} Planning & Strategy: Build a 12-Week System`,
        text: "Create a strong learning plan with weekly goals and review cycles.",
        meta: ["Chris Haroun | 1.5M Students", "9 total hours · 64 lectures · All Levels"],
        rating: "4.7 ★★★★★ (23,806)",
        badges: ["Highest Rated", "Highest Views"],
        price: "Free",
      },
    ],
  }
}
